KeyName: aws-orchestrator
tags:
  Owner: aws-orchestrator
  Environment: ubuntu-desktop
ingress:
  - protocol: TCP
    port: 22
  - protocol: TCP
    port: 3389
instances:
  ubuntu-desktop:
    InstanceType: g4dn.xlarge
    AMI_ID: ami-0493936afbe820b28
    git_repos:
      - https://github.com/hdumcke/aws-orchestrator-configurations.git
    build_scripts:
      - ./aws-orchestrator-configurations/ubuntu-desktop/build.sh
