KeyName: aws-orchestrator
tags:
  Owner: aws-orchestrator
  Environment: simple
instances:
  ubuntu-desktop:
    InstanceType: t2.micro
    AMI_ID: ami-0493936afbe820b28
    git_repos:
      - https://github.com/hdumcke/aws-orchestrator-configurations.git
    build_scripts:
      - ./aws-orchestrator-configurations/ubuntu-desktop/build.sh
